"""init

Revision ID: 691805249468
Revises: 
Create Date: 2026-06-03 22:27:42.000744
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '691805249468'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proxies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('protocol', sa.String(length=10), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('port', sa.String(length=10), nullable=False),
    sa.Column('username', sa.Text(), nullable=True),
    sa.Column('encrypted_password', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proxies_user_id'), 'proxies', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('ad_transparency_searches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('text', sa.String(length=500), nullable=True),
    sa.Column('advertiser_id_query', sa.String(length=100), nullable=True),
    sa.Column('platform', sa.String(length=50), nullable=True),
    sa.Column('creative_format', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('region', sa.String(length=20), nullable=True),
    sa.Column('political_ads', sa.Boolean(), nullable=False),
    sa.Column('num', sa.Integer(), nullable=False),
    sa.Column('next_page_token_input', sa.Text(), nullable=True),
    sa.Column('total_results', sa.Integer(), nullable=True),
    sa.Column('next_page_token_output', sa.Text(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ad_transparency_searches_user_id'), 'ad_transparency_searches', ['user_id'], unique=False)
    op.create_table('affiliate_links',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('affiliate_url', sa.Text(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'affiliate_url', name='uq_affiliate_links_user_url')
    )
    op.create_index(op.f('ix_affiliate_links_affiliate_url'), 'affiliate_links', ['affiliate_url'], unique=False)
    op.create_index(op.f('ix_affiliate_links_domain'), 'affiliate_links', ['domain'], unique=False)
    op.create_index(op.f('ix_affiliate_links_user_id'), 'affiliate_links', ['user_id'], unique=False)
    op.create_table('delegated_mails',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', 'user_id', name='uq_delegated_mail_email_user')
    )
    op.create_index(op.f('ix_delegated_mails_email'), 'delegated_mails', ['email'], unique=False)
    op.create_index(op.f('ix_delegated_mails_user_id'), 'delegated_mails', ['user_id'], unique=False)
    op.create_table('google_ads_searches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('keyword', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('device', sa.String(length=20), nullable=False),
    sa.Column('search_url', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_ads_found', sa.Integer(), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=False),
    sa.Column('organic_links', sa.JSON(), nullable=False),
    sa.Column('final_summary', sa.Text(), nullable=True),
    sa.Column('video_path', sa.Text(), nullable=True),
    sa.Column('video_status', sa.String(length=20), nullable=False),
    sa.Column('proxy_id', sa.String(length=36), nullable=True),
    sa.Column('proxy_name', sa.String(length=100), nullable=True),
    sa.Column('is_scheduled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_google_ads_searches_is_scheduled'), 'google_ads_searches', ['is_scheduled'], unique=False)
    op.create_index(op.f('ix_google_ads_searches_keyword'), 'google_ads_searches', ['keyword'], unique=False)
    op.create_index(op.f('ix_google_ads_searches_user_id'), 'google_ads_searches', ['user_id'], unique=False)
    op.create_table('keyword_planner_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('input_type', sa.String(length=20), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('page_url', sa.Text(), nullable=True),
    sa.Column('use_entire_site', sa.Integer(), nullable=False),
    sa.Column('ads_id', sa.String(length=50), nullable=True),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('location_ids', sa.JSON(), nullable=True),
    sa.Column('result_limit', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keyword_planner_jobs_ads_id'), 'keyword_planner_jobs', ['ads_id'], unique=False)
    op.create_index(op.f('ix_keyword_planner_jobs_input_type'), 'keyword_planner_jobs', ['input_type'], unique=False)
    op.create_index(op.f('ix_keyword_planner_jobs_status'), 'keyword_planner_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_keyword_planner_jobs_user_id'), 'keyword_planner_jobs', ['user_id'], unique=False)
    op.create_table('manual_competitor_searches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('keyword', sa.String(length=255), nullable=False),
    sa.Column('google_url', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('hl', sa.String(length=10), nullable=False),
    sa.Column('gl', sa.String(length=10), nullable=False),
    sa.Column('num', sa.Integer(), nullable=False),
    sa.Column('no_cache', sa.Boolean(), nullable=False),
    sa.Column('total_ads_found', sa.Integer(), nullable=False),
    sa.Column('top_ads_count', sa.Integer(), nullable=False),
    sa.Column('bottom_ads_count', sa.Integer(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manual_competitor_searches_keyword'), 'manual_competitor_searches', ['keyword'], unique=False)
    op.create_index(op.f('ix_manual_competitor_searches_user_id'), 'manual_competitor_searches', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('telegram_subscriptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('topics', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telegram_subscriptions_chat_id'), 'telegram_subscriptions', ['chat_id'], unique=True)
    op.create_index(op.f('ix_telegram_subscriptions_user_id'), 'telegram_subscriptions', ['user_id'], unique=True)
    op.create_table('ad_creatives',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('search_id', sa.String(length=36), nullable=False),
    sa.Column('advertiser_id', sa.String(length=100), nullable=False),
    sa.Column('advertiser', sa.String(length=255), nullable=False),
    sa.Column('ad_creative_id', sa.String(length=100), nullable=False),
    sa.Column('format', sa.String(length=50), nullable=False),
    sa.Column('target_domain', sa.String(length=255), nullable=True),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('link', sa.Text(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('total_days_shown', sa.Integer(), nullable=True),
    sa.Column('first_shown', sa.Integer(), nullable=True),
    sa.Column('last_shown', sa.Integer(), nullable=True),
    sa.Column('details_link', sa.Text(), nullable=True),
    sa.Column('serpapi_details_link', sa.Text(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['search_id'], ['ad_transparency_searches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ad_creatives_ad_creative_id'), 'ad_creatives', ['ad_creative_id'], unique=False)
    op.create_index(op.f('ix_ad_creatives_advertiser_id'), 'ad_creatives', ['advertiser_id'], unique=False)
    op.create_index(op.f('ix_ad_creatives_search_id'), 'ad_creatives', ['search_id'], unique=False)
    op.create_table('ads_accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('mail_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('ads_id', sa.String(length=50), nullable=False),
    sa.Column('ads_name', sa.String(length=255), nullable=False),
    sa.Column('ads_status', sa.String(length=50), nullable=True),
    sa.Column('account_type', sa.String(length=50), nullable=True),
    sa.Column('manager_account_ads_id', sa.String(length=50), nullable=True),
    sa.Column('manager_account_id', sa.String(length=36), nullable=True),
    sa.Column('currency_code', sa.String(length=10), nullable=True),
    sa.Column('timezone', sa.String(length=100), nullable=True),
    sa.Column('budget_paid', sa.Float(), nullable=True),
    sa.Column('budget_used', sa.Float(), nullable=True),
    sa.Column('budget_adjustment', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mail_id'], ['delegated_mails.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['manager_account_id'], ['ads_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mail_id', 'ads_id', name='uq_ads_account_mail_ads')
    )
    op.create_index(op.f('ix_ads_accounts_ads_id'), 'ads_accounts', ['ads_id'], unique=False)
    op.create_index(op.f('ix_ads_accounts_mail_id'), 'ads_accounts', ['mail_id'], unique=False)
    op.create_index(op.f('ix_ads_accounts_user_id'), 'ads_accounts', ['user_id'], unique=False)
    op.create_table('affiliate_link_project_data_scans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('affiliate_link_id', sa.String(length=36), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('project_name', sa.String(length=255), nullable=True),
    sa.Column('project_link', sa.Text(), nullable=True),
    sa.Column('event_content', sa.Text(), nullable=True),
    sa.Column('sale_content', sa.Text(), nullable=True),
    sa.Column('top_countries', sa.JSON(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['affiliate_link_id'], ['affiliate_links.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_affiliate_link_project_data_scans_affiliate_link_id'), 'affiliate_link_project_data_scans', ['affiliate_link_id'], unique=False)
    op.create_table('affiliate_link_traffic_scans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('affiliate_link_id', sa.String(length=36), nullable=False),
    sa.Column('found', sa.Boolean(), nullable=False),
    sa.Column('monthly_visits', sa.Integer(), nullable=False),
    sa.Column('period_month', sa.String(length=7), nullable=False),
    sa.Column('traffic_details', sa.JSON(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['affiliate_link_id'], ['affiliate_links.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_affiliate_link_traffic_scans_affiliate_link_id'), 'affiliate_link_traffic_scans', ['affiliate_link_id'], unique=False)
    op.create_table('author_gmails',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('mail_id', sa.String(length=36), nullable=False),
    sa.Column('refresh_token', sa.String(length=512), nullable=True),
    sa.Column('access_token', sa.String(length=512), nullable=True),
    sa.Column('state', sa.String(length=255), nullable=True),
    sa.Column('code_verifier', sa.String(length=255), nullable=True),
    sa.Column('expires_in', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['mail_id'], ['delegated_mails.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_author_gmails_mail_id'), 'author_gmails', ['mail_id'], unique=True)
    op.create_index(op.f('ix_author_gmails_state'), 'author_gmails', ['state'], unique=False)
    op.create_table('google_ads_search_ads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('search_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('display_url', sa.Text(), nullable=True),
    sa.Column('target_url', sa.Text(), nullable=True),
    sa.Column('advertiser_name', sa.Text(), nullable=True),
    sa.Column('advertiser_domain', sa.Text(), nullable=True),
    sa.Column('advertiser_location', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('landing_page', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['search_id'], ['google_ads_searches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_google_ads_search_ads_search_id'), 'google_ads_search_ads', ['search_id'], unique=False)
    op.create_table('google_ads_search_schedules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('keyword', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('device', sa.String(length=20), nullable=False),
    sa.Column('no_proxy', sa.Boolean(), nullable=False),
    sa.Column('headful', sa.Boolean(), nullable=False),
    sa.Column('proxy_id', sa.String(length=36), nullable=True),
    sa.Column('proxy_name', sa.String(length=100), nullable=True),
    sa.Column('batch_id', sa.String(length=36), nullable=True),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('arq_job_id', sa.String(length=100), nullable=True),
    sa.Column('search_id', sa.String(length=36), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('notification_sent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['search_id'], ['google_ads_searches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_google_ads_search_schedules_batch_id'), 'google_ads_search_schedules', ['batch_id'], unique=False)
    op.create_index(op.f('ix_google_ads_search_schedules_keyword'), 'google_ads_search_schedules', ['keyword'], unique=False)
    op.create_index(op.f('ix_google_ads_search_schedules_run_at'), 'google_ads_search_schedules', ['run_at'], unique=False)
    op.create_index(op.f('ix_google_ads_search_schedules_status'), 'google_ads_search_schedules', ['status'], unique=False)
    op.create_index(op.f('ix_google_ads_search_schedules_user_id'), 'google_ads_search_schedules', ['user_id'], unique=False)
    op.create_table('keyword_planner_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('keyword', sa.Text(), nullable=False),
    sa.Column('avg_monthly_searches', sa.Integer(), nullable=False),
    sa.Column('competition', sa.String(length=50), nullable=False),
    sa.Column('competition_index', sa.Integer(), nullable=True),
    sa.Column('low_top_page_bid', sa.Float(), nullable=True),
    sa.Column('high_top_page_bid', sa.Float(), nullable=True),
    sa.Column('monthly_searches', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['keyword_planner_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keyword_planner_results_job_id'), 'keyword_planner_results', ['job_id'], unique=False)
    op.create_index(op.f('ix_keyword_planner_results_keyword'), 'keyword_planner_results', ['keyword'], unique=False)
    op.create_table('manual_competitor_search_ads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('search_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.String(length=50), nullable=False),
    sa.Column('advertiser', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('snippet', sa.Text(), nullable=False),
    sa.Column('link', sa.Text(), nullable=False),
    sa.Column('sitelinks', sa.JSON(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['search_id'], ['manual_competitor_searches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manual_competitor_search_ads_search_id'), 'manual_competitor_search_ads', ['search_id'], unique=False)
    op.create_table('ad_creative_details',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ad_creative_id', sa.String(length=36), nullable=True),
    sa.Column('advertiser_id', sa.String(length=100), nullable=False),
    sa.Column('google_creative_id', sa.String(length=100), nullable=False),
    sa.Column('format', sa.String(length=50), nullable=True),
    sa.Column('last_shown', sa.Integer(), nullable=True),
    sa.Column('region_name', sa.String(length=100), nullable=True),
    sa.Column('more_ads_by_advertiser', sa.Text(), nullable=True),
    sa.Column('regions', sa.JSON(), nullable=True),
    sa.Column('ad_creatives', sa.JSON(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ad_creative_id'], ['ad_creatives.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ad_creative_details_ad_creative_id'), 'ad_creative_details', ['ad_creative_id'], unique=False)
    op.create_index(op.f('ix_ad_creative_details_advertiser_id'), 'ad_creative_details', ['advertiser_id'], unique=False)
    op.create_index(op.f('ix_ad_creative_details_google_creative_id'), 'ad_creative_details', ['google_creative_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ad_creative_details_google_creative_id'), table_name='ad_creative_details')
    op.drop_index(op.f('ix_ad_creative_details_advertiser_id'), table_name='ad_creative_details')
    op.drop_index(op.f('ix_ad_creative_details_ad_creative_id'), table_name='ad_creative_details')
    op.drop_table('ad_creative_details')
    op.drop_index(op.f('ix_manual_competitor_search_ads_search_id'), table_name='manual_competitor_search_ads')
    op.drop_table('manual_competitor_search_ads')
    op.drop_index(op.f('ix_keyword_planner_results_keyword'), table_name='keyword_planner_results')
    op.drop_index(op.f('ix_keyword_planner_results_job_id'), table_name='keyword_planner_results')
    op.drop_table('keyword_planner_results')
    op.drop_index(op.f('ix_google_ads_search_schedules_user_id'), table_name='google_ads_search_schedules')
    op.drop_index(op.f('ix_google_ads_search_schedules_status'), table_name='google_ads_search_schedules')
    op.drop_index(op.f('ix_google_ads_search_schedules_run_at'), table_name='google_ads_search_schedules')
    op.drop_index(op.f('ix_google_ads_search_schedules_keyword'), table_name='google_ads_search_schedules')
    op.drop_index(op.f('ix_google_ads_search_schedules_batch_id'), table_name='google_ads_search_schedules')
    op.drop_table('google_ads_search_schedules')
    op.drop_index(op.f('ix_google_ads_search_ads_search_id'), table_name='google_ads_search_ads')
    op.drop_table('google_ads_search_ads')
    op.drop_index(op.f('ix_author_gmails_state'), table_name='author_gmails')
    op.drop_index(op.f('ix_author_gmails_mail_id'), table_name='author_gmails')
    op.drop_table('author_gmails')
    op.drop_index(op.f('ix_affiliate_link_traffic_scans_affiliate_link_id'), table_name='affiliate_link_traffic_scans')
    op.drop_table('affiliate_link_traffic_scans')
    op.drop_index(op.f('ix_affiliate_link_project_data_scans_affiliate_link_id'), table_name='affiliate_link_project_data_scans')
    op.drop_table('affiliate_link_project_data_scans')
    op.drop_index(op.f('ix_ads_accounts_user_id'), table_name='ads_accounts')
    op.drop_index(op.f('ix_ads_accounts_mail_id'), table_name='ads_accounts')
    op.drop_index(op.f('ix_ads_accounts_ads_id'), table_name='ads_accounts')
    op.drop_table('ads_accounts')
    op.drop_index(op.f('ix_ad_creatives_search_id'), table_name='ad_creatives')
    op.drop_index(op.f('ix_ad_creatives_advertiser_id'), table_name='ad_creatives')
    op.drop_index(op.f('ix_ad_creatives_ad_creative_id'), table_name='ad_creatives')
    op.drop_table('ad_creatives')
    op.drop_index(op.f('ix_telegram_subscriptions_user_id'), table_name='telegram_subscriptions')
    op.drop_index(op.f('ix_telegram_subscriptions_chat_id'), table_name='telegram_subscriptions')
    op.drop_table('telegram_subscriptions')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_manual_competitor_searches_user_id'), table_name='manual_competitor_searches')
    op.drop_index(op.f('ix_manual_competitor_searches_keyword'), table_name='manual_competitor_searches')
    op.drop_table('manual_competitor_searches')
    op.drop_index(op.f('ix_keyword_planner_jobs_user_id'), table_name='keyword_planner_jobs')
    op.drop_index(op.f('ix_keyword_planner_jobs_status'), table_name='keyword_planner_jobs')
    op.drop_index(op.f('ix_keyword_planner_jobs_input_type'), table_name='keyword_planner_jobs')
    op.drop_index(op.f('ix_keyword_planner_jobs_ads_id'), table_name='keyword_planner_jobs')
    op.drop_table('keyword_planner_jobs')
    op.drop_index(op.f('ix_google_ads_searches_user_id'), table_name='google_ads_searches')
    op.drop_index(op.f('ix_google_ads_searches_keyword'), table_name='google_ads_searches')
    op.drop_index(op.f('ix_google_ads_searches_is_scheduled'), table_name='google_ads_searches')
    op.drop_table('google_ads_searches')
    op.drop_index(op.f('ix_delegated_mails_user_id'), table_name='delegated_mails')
    op.drop_index(op.f('ix_delegated_mails_email'), table_name='delegated_mails')
    op.drop_table('delegated_mails')
    op.drop_index(op.f('ix_affiliate_links_user_id'), table_name='affiliate_links')
    op.drop_index(op.f('ix_affiliate_links_domain'), table_name='affiliate_links')
    op.drop_index(op.f('ix_affiliate_links_affiliate_url'), table_name='affiliate_links')
    op.drop_table('affiliate_links')
    op.drop_index(op.f('ix_ad_transparency_searches_user_id'), table_name='ad_transparency_searches')
    op.drop_table('ad_transparency_searches')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_proxies_user_id'), table_name='proxies')
    op.drop_table('proxies')
    # ### end Alembic commands ###
