"""init

Revision ID: 6ca679b9dd70
Revises: 
Create Date: 2026-05-28 00:56:33.322127
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '6ca679b9dd70'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('ad_transparency_searches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('text', sa.String(length=500), nullable=True),
    sa.Column('advertiser_id_query', sa.String(length=100), nullable=True),
    sa.Column('platform', sa.String(length=50), nullable=True),
    sa.Column('creative_format', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('region', sa.String(length=20), nullable=True),
    sa.Column('political_ads', sa.Boolean(), nullable=False),
    sa.Column('num', sa.Integer(), nullable=False),
    sa.Column('next_page_token_input', sa.Text(), nullable=True),
    sa.Column('total_results', sa.Integer(), nullable=True),
    sa.Column('next_page_token_output', sa.Text(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ad_transparency_searches_user_id'), 'ad_transparency_searches', ['user_id'], unique=False)
    op.create_table('ad_creatives',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('search_id', sa.String(length=36), nullable=False),
    sa.Column('advertiser_id', sa.String(length=100), nullable=False),
    sa.Column('advertiser', sa.String(length=255), nullable=False),
    sa.Column('ad_creative_id', sa.String(length=100), nullable=False),
    sa.Column('format', sa.String(length=50), nullable=False),
    sa.Column('target_domain', sa.String(length=255), nullable=True),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('link', sa.Text(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('total_days_shown', sa.Integer(), nullable=True),
    sa.Column('first_shown', sa.Integer(), nullable=True),
    sa.Column('last_shown', sa.Integer(), nullable=True),
    sa.Column('details_link', sa.Text(), nullable=True),
    sa.Column('serpapi_details_link', sa.Text(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['search_id'], ['ad_transparency_searches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ad_creatives_ad_creative_id'), 'ad_creatives', ['ad_creative_id'], unique=False)
    op.create_index(op.f('ix_ad_creatives_advertiser_id'), 'ad_creatives', ['advertiser_id'], unique=False)
    op.create_index(op.f('ix_ad_creatives_search_id'), 'ad_creatives', ['search_id'], unique=False)
    op.create_table('ad_creative_details',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ad_creative_id', sa.String(length=36), nullable=True),
    sa.Column('advertiser_id', sa.String(length=100), nullable=False),
    sa.Column('google_creative_id', sa.String(length=100), nullable=False),
    sa.Column('format', sa.String(length=50), nullable=True),
    sa.Column('last_shown', sa.Integer(), nullable=True),
    sa.Column('region_name', sa.String(length=100), nullable=True),
    sa.Column('more_ads_by_advertiser', sa.Text(), nullable=True),
    sa.Column('regions', sa.JSON(), nullable=True),
    sa.Column('ad_creatives', sa.JSON(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ad_creative_id'], ['ad_creatives.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ad_creative_details_ad_creative_id'), 'ad_creative_details', ['ad_creative_id'], unique=False)
    op.create_index(op.f('ix_ad_creative_details_advertiser_id'), 'ad_creative_details', ['advertiser_id'], unique=False)
    op.create_index(op.f('ix_ad_creative_details_google_creative_id'), 'ad_creative_details', ['google_creative_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ad_creative_details_google_creative_id'), table_name='ad_creative_details')
    op.drop_index(op.f('ix_ad_creative_details_advertiser_id'), table_name='ad_creative_details')
    op.drop_index(op.f('ix_ad_creative_details_ad_creative_id'), table_name='ad_creative_details')
    op.drop_table('ad_creative_details')
    op.drop_index(op.f('ix_ad_creatives_search_id'), table_name='ad_creatives')
    op.drop_index(op.f('ix_ad_creatives_advertiser_id'), table_name='ad_creatives')
    op.drop_index(op.f('ix_ad_creatives_ad_creative_id'), table_name='ad_creatives')
    op.drop_table('ad_creatives')
    op.drop_index(op.f('ix_ad_transparency_searches_user_id'), table_name='ad_transparency_searches')
    op.drop_table('ad_transparency_searches')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
